헬스체크 추가

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -55,7 +55,8 @@ jobs:
           script: |
 
             # 기존에 실행 중인 spring-miruni-backend 컨테이너가 있으면 종료 및 삭제
-            docker rm -f spring-miruni-backend || true
+            docker stop spring-miruni-backend || true
+            docker rm spring-miruni-backend || true
 
             # 최신 이미지 다운로드
             docker pull ${{ secrets.DOCKER_USERNAME }}/spring-miruni-backend:latest
@@ -77,8 +78,9 @@ jobs:
             echo "Waiting for application to start..."
             sleep 10  # Spring Boot 부팅 대기
             echo "Performing health check..."
-            curl --fail http://localhost:8080/actuator/health || (echo "Health check failed" && exit 1)
-            echo "Health check passed!"
+            curl --fail http://localhost:8080/actuator/health \
+              && echo "Health check passed!" \
+              || (echo "Health check failed" && docker logs spring-miruni-backend && exit 1)
 
 
 
